defaults:
  - _self_

project_name: Cloud Annotation
hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/push/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

secrets:
  dotenv: ${hydra:runtime.cwd}/configs/cloud_annotation/.env

criteria:
  prod_selection_query: data_pipeline.utils.db_queries.fetch_latest_approved_products
  query_params:
    min_cloud: 5
    max_cloud: 20
    created_after: 2025-08-01T00:00:00Z
    created_before: 2025-09-05T00:00:00Z

logging:
  logdir: ${as_path:${hydra:runtime.cwd}/logs/scripts/push}
  console_fmt: >-
    <green>{time:YYYY/MM/DD-HH:mm:ss!UTC}</green> |
    <level>{level: <8}</level> |
    <cyan>{name}:{function}:{line}</cyan> -
    <level>{message}</level>
  file_fmt: "{time:YYYY MM DD HH:mm:ss!UTC} | {level: <8} | {message}"
  noisy_pkgs:
    - encord
    - frame-aligner

job_processor:
  dst_bucket_folder: cloud_annotations
  bucket_root_folder: encord_cloud_data
  query_success: data_pipeline.utils.db_queries.insert_cloud_annotation_row
  query_failure: data_pipeline.utils.db_queries.write_exception
  allow_overwriting: false 
  dry_run: false
  encord_payload_dst: ${hydra:runtime.cwd}/configs/encord_payload.json 
  cuda_device: 1



