defaults:
  - _self_

project_name: Cloud Annotation
hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/hydra/push/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

criteria:
  artifact_destination: ${as_path:/bigdata/datasets_analytics/clouds/hf1a_reflectance/pipeline_test}
  prod_selection_query: data_pipeline.utils.db_queries.fetch_all_products_paths_that_passed_qc
  starting_date: 2025-08-01
  min_cloud_coverage: 10

logging:
  logdir: ${as_path:${hydra:runtime.cwd}/logs/scripts/push}
  console_fmt: >-
    <green>{time:YYYY/MM/DD-HH:mm:ss!UTC}</green> |
    <level>{level: <8}</level> |
    <cyan>{name}:{function}:{line}</cyan> -
    <level>{message}</level>
  file_fmt: "{time:YYYY MM DD HH:mm:ss!UTC} | {level: <8} | {message}"
  noisy_pkgs:
    - encord
    - frame-aligner

job_processor:
  query_success: data_pipeline.utils.db_queries.mark_annotation_processed
  query_failure: data_pipeline.utils.db_queries.write_exception
  allow_overwriting: true 
  dry_run: true

secrets:
  dotenv: ${hydra:runtime.cwd}/configs/cloud_annotation/.env